# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('desc', models.CharField(max_length=1000, verbose_name='模块描述')),
                ('manager', models.CharField(max_length=100, verbose_name='管理员')),
                ('status', models.IntegerField(blank=True, choices=[(0, '正常'), (-1, '删除')], default=0, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '模块列表',
                'verbose_name': '模块列表',
            },
        ),
    ]
